from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
from pptx.dml.color import RGBColor
import random
from prompt import generate_slide_content, generate_title_subtitle, generate_summary_points

def apply_background_gradient(slide, color1, color2):

    background = slide.background
    fill = background.fill
    fill.solid()
    fill.fore_color.rgb = color1
    

def generate_presentation(topic, num_slides, output_path):
    prs = Presentation()
    prs.slide_width = Inches(10)
    prs.slide_height = Inches(7.5)

    themes = [
        {
            "name": " Baby Blue ",
            "bg": RGBColor(255, 255, 255),
            "accent": RGBColor(37, 99, 235),  
            "title": RGBColor(15, 23, 42),    
            "text": RGBColor(51, 65, 85),     
            "subtitle": RGBColor(100, 116, 139)  
        },
        {
            "name": " Modern Dark ",
            "bg": RGBColor(15, 23, 42),       
            "accent": RGBColor(59, 130, 246),  
            "title": RGBColor(248, 250, 252),  
            "text": RGBColor(226, 232, 240),   
            "subtitle": RGBColor(148, 163, 184)  
        },
        {
            "name": " White ",
            "bg": RGBColor(249, 250, 251),    
            "accent": RGBColor(79, 70, 229),   
            "title": RGBColor(17, 24, 39),     
            "text": RGBColor(55, 65, 81),      
            "subtitle": RGBColor(107, 114, 128)  
        },
        {
            "name": " Navy ",
            "bg": RGBColor(255, 255, 255),
            "accent": RGBColor(30, 58, 138),  
            "title": RGBColor(30, 58, 138),
            "text": RGBColor(31, 41, 55),     
            "subtitle": RGBColor(75, 85, 99)   
        }
    ]
    theme = random.choice(themes)

    title_slide = prs.slides.add_slide(prs.slide_layouts[6])
    apply_background_gradient(title_slide, theme["bg"], theme["bg"])
    
    accent_bar = title_slide.shapes.add_shape(1,Inches(0), Inches(0), Inches(10), Inches(0.3))
    accent_bar.fill.solid()
    accent_bar.fill.fore_color.rgb = theme["accent"]
    accent_bar.line.fill.background()

    title_box = title_slide.shapes.add_textbox(Inches(1), Inches(2.5), Inches(8), Inches(1.5))
    title_frame = title_box.text_frame
    title_frame.word_wrap = True
    p = title_frame.paragraphs[0]
    p.text = topic

    p.font.name = "Montserrat"
    p.font.size = Pt(54)
    p.font.bold = True
    p.font.color.rgb = theme["title"]
    p.alignment = PP_ALIGN.CENTER

    subtitle_text = generate_title_subtitle(topic)
    subtitle_box = title_slide.shapes.add_textbox(Inches(1), Inches(4.2), Inches(8), Inches(0.8))
    subtitle_frame = subtitle_box.text_frame
    subtitle_frame.word_wrap = True
    p = subtitle_frame.paragraphs[0]
    p.text = subtitle_text
    p.font.name = "Lato"
    p.font.size = Pt(22)
    p.font.color.rgb = theme["subtitle"]
    p.alignment = PP_ALIGN.CENTER

    footer_box = title_slide.shapes.add_textbox(Inches(1), Inches(6.5), Inches(8), Inches(0.5))
    footer_frame = footer_box.text_frame
    p = footer_frame.paragraphs[0]
    p.text = "Generated by GenSpark Lite"
    p.font.name = "Lato"
    p.font.size = Pt(12)
    p.font.color.rgb = theme["subtitle"]
    p.alignment = PP_ALIGN.CENTER

    content_slides_count = num_slides - 3  

    for i in range(1, content_slides_count + 1):
        slide = prs.slides.add_slide(prs.slide_layouts[6])
        apply_background_gradient(slide, theme["bg"], theme["bg"])
        
        accent_bar = slide.shapes.add_shape(1, Inches(0), Inches(0), Inches(10), Inches(0.15))
        accent_bar.fill.solid()
        accent_bar.fill.fore_color.rgb = theme["accent"]
        accent_bar.line.fill.background()

        section_title, points = generate_slide_content(topic, i, content_slides_count)

        slide_num_box = slide.shapes.add_textbox(Inches(9.2), Inches(0.3), Inches(0.6), Inches(0.3))
        slide_num_frame = slide_num_box.text_frame
        p = slide_num_frame.paragraphs[0]
        p.text = f"{i}"
        p.font.name = "Lato"
        p.font.size = Pt(14)
        p.font.color.rgb = theme["subtitle"]
        p.alignment = PP_ALIGN.CENTER

        title_box = slide.shapes.add_textbox(Inches(0.8), Inches(0.8), Inches(8.4), Inches(0.8))
        title_frame = title_box.text_frame
        title_frame.word_wrap = True
        p = title_frame.paragraphs[0]
        p.text = section_title
        p.font.name = "Montserrat"
        p.font.size = Pt(36)
        p.font.bold = True
        p.font.color.rgb = theme["title"]
        p.alignment = PP_ALIGN.LEFT

        content_box = slide.shapes.add_textbox(Inches(0.8), Inches(2), Inches(8.4), Inches(4.5))
        content_frame = content_box.text_frame
        content_frame.word_wrap = True
        content_frame.vertical_anchor = MSO_ANCHOR.TOP
        
        for idx, point in enumerate(points):
            p = content_frame.add_paragraph() if idx > 0 else content_frame.paragraphs[0]
            p.text = f"• {point}"
            p.font.name = "Open Sans"
            p.font.size = Pt(18)
            p.font.color.rgb = theme["text"]
            p.space_before = Pt(12)
            p.space_after = Pt(8)
            p.line_spacing = 1.3
            p.level = 0

    summary_slide = prs.slides.add_slide(prs.slide_layouts[6])
    apply_background_gradient(summary_slide, theme["bg"], theme["bg"])
    
    accent_bar = summary_slide.shapes.add_shape(1, Inches(0), Inches(0), Inches(10), Inches(0.15))
    accent_bar.fill.solid()
    accent_bar.fill.fore_color.rgb = theme["accent"]
    accent_bar.line.fill.background()

    title_box = summary_slide.shapes.add_textbox(Inches(0.8), Inches(0.8), Inches(8.4), Inches(0.8))
    title_frame = title_box.text_frame
    p = title_frame.paragraphs[0]
    p.text = "Key Takeaways"
    p.font.name = "Montserrat"
    p.font.size = Pt(42)
    p.font.bold = True
    p.font.color.rgb = theme["title"]
    p.alignment = PP_ALIGN.CENTER

    summary_points = generate_summary_points(topic, num_slides)
    content_box = summary_slide.shapes.add_textbox(Inches(1.5), Inches(2.2), Inches(7), Inches(4))
    content_frame = content_box.text_frame
    content_frame.word_wrap = True
    
    for idx, point in enumerate(summary_points):
        p = content_frame.add_paragraph() if idx > 0 else content_frame.paragraphs[0]
        p.text = f"{idx + 1}. {point}"
        p.font.name = "Open Sans"
        p.font.size = Pt(20)
        p.font.color.rgb = theme["text"]
        p.space_before = Pt(16)
        p.space_after = Pt(12)
        p.line_spacing = 1.3

    questions_slide = prs.slides.add_slide(prs.slide_layouts[6])
    apply_background_gradient(questions_slide, theme["bg"], theme["bg"])
    
    accent_bar = questions_slide.shapes.add_shape(1, Inches(0), Inches(0), Inches(10), Inches(0.3))
    accent_bar.fill.solid()
    accent_bar.fill.fore_color.rgb = theme["accent"]
    accent_bar.line.fill.background()

    textbox = questions_slide.shapes.add_textbox(Inches(1), Inches(2.8), Inches(8), Inches(1.5))
    frame = textbox.text_frame
    p = frame.paragraphs[0]
    p.text = "Questions?"
    p.font.name = "Montserrat"
    p.font.size = Pt(56)
    p.font.bold = True
    p.font.color.rgb = theme["title"]
    p.alignment = PP_ALIGN.CENTER

    subtext = questions_slide.shapes.add_textbox(Inches(1), Inches(4.5), Inches(8), Inches(0.6))
    sub_frame = subtext.text_frame
    p = sub_frame.paragraphs[0]
    p.text = "Let's discuss your thoughts and ideas"
    p.font.name = "Lato"
    p.font.size = Pt(20)
    p.font.color.rgb = theme["subtitle"]
    p.alignment = PP_ALIGN.CENTER

    thanks_slide = prs.slides.add_slide(prs.slide_layouts[6])
    apply_background_gradient(thanks_slide, theme["bg"], theme["bg"])
    
    accent_bar = thanks_slide.shapes.add_shape(1, Inches(0), Inches(0), Inches(10), Inches(0.3))
    accent_bar.fill.solid()
    accent_bar.fill.fore_color.rgb = theme["accent"]
    accent_bar.line.fill.background()

    textbox = thanks_slide.shapes.add_textbox(Inches(1), Inches(2.5), Inches(8), Inches(1.5))
    frame = textbox.text_frame
    p = frame.paragraphs[0]
    p.text = "Thank You"
    p.font.name = "Montserrat"
    p.font.size = Pt(60)
    p.font.bold = True
    p.font.color.rgb = theme["title"]
    p.alignment = PP_ALIGN.CENTER

    subtext = thanks_slide.shapes.add_textbox(Inches(1), Inches(4.3), Inches(8), Inches(0.6))
    sub_frame = subtext.text_frame
    p = sub_frame.paragraphs[0]
    p.font.name = "Lato"
    p.font.size = Pt(20)
    p.font.color.rgb = theme["subtitle"]
    p.alignment = PP_ALIGN.CENTER

    prs.save(output_path)